const express = require('express');
const router = express.Router();
const otControllers = require('../controllers/otControllers');

router.get('/otlist/:id', otControllers.list);
router.get('/otlistlast/:id', otControllers.listlast);
router.get('/listhistory_no/:id', otControllers.listhistory_no);
router.get('/listhistory_yes/:id', otControllers.listhistory_yes);
router.get('/ot/add/:id', otControllers.add);
router.post('/ot/save', otControllers.save);
router.get('/ot/del/:id', otControllers.del);
router.get('/ot/delete/:id', otControllers.delete);
router.get('/ot/edit/:id', otControllers.edit);
router.post('/ot/update/:id', otControllers.update);
router.get('/ot/editlast/:id', otControllers.editlast);
router.get('/ot/offset_time_ot_list/:id', otControllers.offot_list);
router.get('/ot/offset_time_ot_add/:id', otControllers.offot_add);
router.get('/ot/ottimeList/:id', otControllers.ottimeList);
router.get('/ot/otcompensateList/:id', otControllers.otcompensateList);
router.post('/ot/updatelast/:id', otControllers.updatelast);
router.post('/ot/approval/:id', otControllers.approval);
router.post('/ot/approvallast/:id', otControllers.approvallast);
router.post('/ot/disapproval/:id', otControllers.disapproval);
router.post('/ot/confirm_ot/:id', otControllers.confirm_ot);
router.post('/ot/offset_time_ot', otControllers.save_source_destination);
router.get('/otlistleaderl/:department_id', otControllers.listleader);
router.get('/otlistleaderinstall', otControllers.listleaderinstall);
router.get('/otlistleaderMa', otControllers.listleaderMa);
router.get('/otlistleaderinstallandMa', otControllers.listleaderInstallAndMA);
router.get('/ot/History_noleader/:department_id', otControllers.otHistory_noleader);
router.get('/ot/History_noleaderinstall', otControllers.otHistory_noleaderinstall);
router.get('/ot/History_noleaderleaderMa', otControllers.otHistory_noleaderleaderMa);
router.get('/ot/History_noleaderInstallAndMA', otControllers.otHistory_noleaderInstallAndMA);
router.get('/ot/History_noleaderhistory/:id', otControllers.otHistory_noleaderhistory);
router.get('/ot/History_noleaderinstallhistory/:id', otControllers.otHistory_noleaderinstallhistory);
router.get('/ot/History_noleaderleaderMahistory/:id', otControllers.otHistory_noleaderleaderMahistory);
router.get('/ot/History_noleaderInstallAndMAhistory/:id', otControllers.otHistory_noleaderInstallAndMAhistory);
router.get('/ot/History_yesleader/:department_id', otControllers.otHistory_yesleader);
router.get('/ot/History_yesleaderinstall', otControllers.otHistory_yesleaderinstall);
router.get('/ot/History_yesleaderleaderMa', otControllers.otHistory_yesleaderleaderMa);
router.get('/ot/History_yesleaderInstallAndMA', otControllers.otHistory_yesleaderInstallAndMA);
router.get('/ot/History_yesleaderhistory/:id', otControllers.otHistory_yesleaderhistory);
router.get('/ot/History_yesleaderinstallhistory/:id', otControllers.otHistory_yesleaderinstallhistory);
router.get('/ot/History_yesleaderMahistory/:id', otControllers.otHistory_yesleaderMahistory);
router.get('/ot/History_yesleaderInstallAndMAhistory/:id', otControllers.otHistory_yesleaderInstallAndMAhistory);
router.get('/ot/timeListleader/:department_id', otControllers.ottimeListleader);
router.get('/ot/timeListleaderinstall', otControllers.ottimeListleaderinstall);
router.get('/ot/timeListleaderMa', otControllers.ottimeListleaderMa);
router.get('/ot/timeListleaderInstallAndMA', otControllers.ottimeListleaderInstallAndMA);
router.get('/ot/timeListleaderhistory/:id', otControllers.timeListleaderhistory);
router.get('/ot/timeListleaderinstallhistory/:id', otControllers.timeListleaderinstallhistory);
router.get('/ot/timeListleaderMahistory/:id', otControllers.timeListleaderMahistory);
router.get('/ot/timeListleaderinstallandMahistory/:id', otControllers.timeListleaderinstallandMahistory);
router.get('/ot/otcompensateListleader/:department_id', otControllers.otcompensateListleader);
router.get('/ot/otcompensateListleaderinstall', otControllers.otcompensateListleaderinstall);
router.get('/ot/otcompensateListleaderMa', otControllers.otcompensateListleaderMa);
router.get('/ot/otcompensateListInstallAndMA', otControllers.otcompensateListInstallAndMA);
router.get('/ot/otcompensateListleaderhistory/:id', otControllers.otcompensateListleaderhistory);
router.get('/ot/otcompensateListleaderinstallhistory/:id', otControllers.otcompensateListleaderinstallhistory);
router.get('/ot/otcompensateListleaderMahistory/:id', otControllers.otcompensateListleaderMahistory);
router.get('/ot/otcompensateListleaderinstallandMahistory/:id', otControllers.otcompensateListleaderinstallandMahistory);
router.get('/otlistadmin', otControllers.listadmin);
router.get('/otlistlastadmin', otControllers.listlastAdmin);
router.get('/listhistory_noadmin', otControllers.listhistory_noAdmin);
router.get('/listhistory_yesadmin', otControllers.listhistory_yesAdmin);
router.get('/otlistall', otControllers.listall); 
router.get('/otlistadmin/del/:id', otControllers.listadmin);
router.get('/ot/offlistall', otControllers.offot_listAdmin);
router.get('/ot/offot_listAdmin', otControllers.offot_listAdminhome);
router.get('/ot/otcompensateListadmin', otControllers.otcompensateListAdminhome);
router.get('/ot/ottimeListAdmin', otControllers.ottimeListAdmin);
router.get('/ot/otcompensateListadminhistory/:id', otControllers.otcompensateListAdminhomeList);
router.get('/ot/ottimeListAdminhistory/:id', otControllers.ottimeListAdminhistory);
router.get('/ot/delotcompensateListadminhistorydel/:id', otControllers.delotcompensateListadminhistory);
router.get('/ot/delotcompensateListadminhistorydelelte/:id', otControllers.deletedelotcompensateListadminhistory);
router.get('/ot/listhistory_yesAdminhistory/:id', otControllers.listhistory_yesAdminhistory);
router.get('/ot/listhistory_noAdminhistory/:id', otControllers.listhistory_noAdminhistory)


module.exports = router;

    